Fairmat 2024: proposal on electron microscopy (EM)
nexusformat/definitions pull request #1423
Opened 2024-09-24 08:07 UTC by lukaspie

2025-02-27 22:55 UTC, phyy-nx commented
@lukaspie do you have a rendered version of this PR hosted somewhere?

2025-02-28 13:27 UTC, mkuehbach commented
@phyy-nx if you are on the latest commit of this branch and deactivate the -W in the html part of the make local Makefile, you can compile locally and then use the respective HTML from the applications/NXem.html
I am currently working on going through this branch again to edit the following issues:
- [ ] Rebase against current NIAC main
- [ ] Refactoring of NXserialized and NXidentifier, adding nameType hints were required for clarification, and using NXcomponent now throughout instead of NXobject, other than this I am not planning to make substantial design changes.

2025-03-06 10:02 UTC, mkuehbach commented
Dear Aaron @phyy-nx and Herbert @yayahjb thank you very much for your feedback. I would like to inform you that this PR is feature complete on our side.

2025-03-21 23:36 UTC, phyy-nx requested changes
I have only reviewed NXem.nxdl.xml itself so far.  Some notes.

There are lots of required fields.  This can be fine, but just as a general vibe check, is it worth reviewing what is required and what could be recommended instead?

There are a lot of undocumented groups and files.

Most importantly, I don't have a sense for the overall whole.  How are the groups put together? This application definition will be by far the longest in NeXus, and indeed will comprise nearly 25% of all the lines in the applications folder.  Is it worth having a larger overview at the top of the document?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                    why one may wish to store the density of the specimen.
Delete the last bit?  'why one may wish...'

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                    </enumeration>
This enumeration is scary.  What is going on here that couldn't be done with NXtransformations?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                    </enumeration>
Cardinal words?  I recognize this may be part of #1415 which I haven't reviewed yet.

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +        <group name="measurement" type="NXobject" optional="true">
NXobject?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +hence using optional is sufficient-->
Developer comments needed?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                        Instances should use detector_reference_frame as a name prefix.
So should this be detector_reference_frame_DETECTOR_REFERENCE_FRAME with nameType="partial"?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                        Instances should use control_software as a name prefix.
So should this field be named control_software_PROGRAM with nameType="partial"?  This comment applies to other parts of the definition with the pattern "Instances should use XXX as a name prefix."

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                    from the static one.
Alternative:
Event-related (meta)data,  typically measured datasets like images and spectra. To avoid repetitively storing static instrument-related metadata,  the dynamic (meta)data that typically changes for each image and spectrum is split from the static (meta)data.

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                           Each NXimage instance must use only one image or stack instance.
Stack instance?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                                    <group name="c_1" type="NXaberration" optional="true">
What are all these c_1, a_1, etc. fields?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +        <group name="simulation" type="NXobject" optional="true">
NXobject?

2025-03-21 23:36 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                <group name="pattern_centre" type="NXprocess" recommended="true">
Ooph, center vs. centre rears its ugly head yet again...

2025-03-24 14:10 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                                    <group name="c_1" type="NXaberration" optional="true">
Individual named aberration coefficients, all "specified", following the naming convention of the electron microscopy community.

2025-03-24 14:13 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                <group name="pattern_centre" type="NXprocess" recommended="true">
Yeah I should use American spelling

2025-04-14 17:02 UTC, phyy-nx commented
This PR has NXobject listed as groups due to not having an appropriate base class for them.  List of NXobjects in this proposal:
- measurement
- events
- simulation
- INTERACTION_VOLUME
- ROI

In all cases, `NXobject` is being used as a 'bucket' to group other base classes, without needing to define a new base class for the bucket.  Example, we have `NXevent_data_em` as a new base class, but we are not adding a new base class`NXevents_list` which would serve as a bucket with a defined type, instead we have `events` of type `NXobject`.

Options:
1. Accept that NXobject can be used as a 'bucket' for grouping objects in application definitions.  If multiple NXobjects are in a group, distinguish them with named prefixes using nameType=partial
2. Add a new base class `NXbag`, which just lets you group objects together without needing a new bucket class.
3. Go back to the original implementaion, where the above 5 NXobjects are new base classes.  This is the current precedent in NeXus (example `NXdetector_group`), but will lead to a lot of new tiny base classes.

NIAC: which of these options is best?  They all have merit.

2025-04-14 17:02 UTC, phyy-nx commented
Also from Telco: change this pattern:

"Instances should use interaction_volume as a name prefix."

To naming the group interaction_volumeSUFFIX with nameType=partial

2025-04-30 16:24 UTC, phyy-nx commented
From Telco Apr 30 2025.  Adopt 3. above: Go back to the original implementaion, where the above 5 NXobjects are new base classes. This is the current precedent in NeXus (example NXdetector_group), but will lead to a lot of new tiny base classes.

Continue to investigate #1428, which reorganizes the base classes web page to add groupings, similar to https://manual.nexusformat.org/classes/contributed_definitions/index.html#contributed-definitions

Again, thanks for your contributions.

2025-05-09 11:06 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                <group name="pattern_centre" type="NXprocess" recommended="true">
Has been addressed in the new draft on the fairmat side, ones I am done with all changes, will update this PR here as well

2025-05-09 11:06 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                                    <group name="c_1" type="NXaberration" optional="true">
Comment can be resolved as it was just to communicate purpose

2025-05-09 11:13 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                           Each NXimage instance must use only one image or stack instance.
I removed this docstring as it might have been misleading, key point is NXimage provides specific specialized NXdata schema instances for commonly used data observed in EM, using and offering NXdata alone I do not want as this gives still substantial variety as how people can go about naming things. The idea of using specializations like image_oned, twod and stack_ is to convey meaning that there are different types of NXdata but not at the same time be too restrictive, one can always add anyway NXdata instances in HDF5 files irrespective if one follows NXem which is then using "just the NeXus base classes" if people really need this flexiibility in FAIRmat we learned that giving people too much flexibility on how to name things again just adds mess and demands then additional parsing code to extract context.

2025-05-09 11:14 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    from the static one.
Suggestion accepted in the new draft

2025-05-09 11:16 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                        Instances should use control_software as a name prefix.
Yes, this suggestion has been accepted, in the new draft all instances of design pattern "nameType: any" with docstring "Instances should" have been replaced according to the above-mentioned suggestion as it was also discussed at the last telco

2025-05-09 11:17 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                        Instances should use detector_reference_frame as a name prefix.
Yes, like for all other cases of this pattern, I will resolve all matching comments on these as these have been reworked

2025-05-09 11:19 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +hence using optional is sufficient-->
Have removed them, if needed they are part of the history

2025-05-09 11:20 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +        <group name="measurement" type="NXobject" optional="true">
Refactored to tiny base class NXem_measurement
The use of new such tiny base classes whose purpose is mainly that of an NXbag with validation possible has been kept to a minimum see also the following comment https://github.com/FAIRmat-NFDI/nexus_definitions/commit/9a1f44cc07617b2646ac149fc4431333614f9d5e

2025-05-09 11:25 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    </enumeration>
Yes, but relaxed into an open enumeration

2025-05-09 11:35 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    why one may wish to store the density of the specimen.
Removed in the new draft following your suggestion

2025-05-09 11:36 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    the usage of this field is discouraged and instead an instance of a region-of-interest within connection to individual :ref:`NXevent_data_em`
Suggestion taken, thank you

2025-05-09 11:37 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    An alias used to refer to the specimen to please readability for humans.
Suggestion followed

2025-05-09 11:40 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    Additional time stamps prior to preparation_date should better be placed in resources
Suggestion taken

2025-05-09 11:41 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    connected metadata is considered as within the responsibility of the
Suggestion taken

2025-05-09 11:43 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    Identifier of the sample from which the sample was cut or the string *None*,
Suggestion taken, does the addition of ```cut off``` solve your comment about ```cut``` ?

2025-05-09 11:43 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    i.e. the parent to this sample.
Suggestion taken

2025-05-09 11:43 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    the specific sample, whose results are stored by this :ref:`NXentry` instance because a single
Grammar fixed

2025-05-09 11:46 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    and especially the predecessor/origin from where that sample was cut.  The terms sample
Clarification added, does this resolve the comment?

2025-05-09 11:47 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                    This field must not be used for an alias for the sample! Instead, use name.
Solved via docstring edit

2025-05-09 11:48 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                demand an unnecessary duplication though of many details about the instrument.
Edited following your suggestion, thank you

2025-05-09 11:48 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                If multiple samples are investigated storing each of them in an own ENTRY group eventually will
Edited following your suggestion

2025-05-09 11:49 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                This can be avoided by using another strategy how to store all samples and their results.
Suggestion followed

2025-05-09 11:50 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                for which of the samples loaded the (characterization) event was detected.
Suggestion taken

2025-05-09 11:51 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                Instances should use user as a name prefix.
Removed the others

2025-05-09 11:56 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                during parsing to NeXus.
Oopps, yes too complicated, I rewrote the sentence to make my point clearer.

2025-05-09 11:58 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                start_time and end_time together.
Plain ISO8601 string is fine, which additional benefit does making this a reference link bring?

2025-05-09 12:00 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                something, eg if an idea is correct*).
Followed the suggestion

2025-05-09 12:00 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                Ideally, a (globally) unique persistent identifier for referring to this experiment.
Followed the suggestion

2025-05-09 12:02 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                current base classes need extension based on user feedback.
Agreed

2025-05-09 12:02 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +
Suggestion taken

2025-05-09 12:03 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +-| recommended: xref part ideally also as a list of triple (spec, term, url to uri)-->
Done

2025-05-09 12:03 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +        physical mechanisms and phenomena or to characterize materials with an electron microscope.
Suggestion taken

2025-05-09 12:04 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +        controlled electron beams are used for studying electron-beam matter interaction to explore
Suggestion taken,

2025-05-09 12:05 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +        of electron microscopy
Accepted

2025-05-09 12:11 UTC, mkuehbach commented
The three points on refactoring use of NXobject as an NXbag and comments have been addressed in here: https://github.com/FAIRmat-NFDI/nexus_definitions/tree/emapm_prepare_niac_voting
I will now go through the NXem appdef ones more and then update the respective files in this PR. I will leave a note when this is done to allow a re-review of the proposal

2025-05-09 12:17 UTC, mkuehbach commented
There was an introductory comment on the complexity and length of the appdef and that it seems to demand many required fields. Here it was discussed already at the telco that most required fields are within optional groups and thereby the NXem does not require a substantial larger set of concepts populated.

The top-level structuring groups user, coordinate systems, roi, simulation, and even measurements are optional or recommended, i.e. not mandatory, this design of incremental requirements where most groups are optional or recommend and only their childs made required I am convinced is a reasonable compromise for an appdef that needs to cover such a diverse instrument and research field.

2025-05-11 23:00 UTC, phyy-nx commented
@mkuehbach can you resolve conflicts and merge in master? Then I can go through and resolve comments.

2025-05-12 09:54 UTC, mkuehbach commented
@phyy-nx @lukaspie @sanbrock  I integrated what I wanted to integrate still, I also fixed the pipeline, I am done with this, this is ready for re-review !

The only missing point is a few edits in the domain specific em-manual.rst for the documentation but the NXDL XML and tests are fine.

2025-05-13 19:30 UTC, phyy-nx commented
@mkuehbach can you post a link to a rendered version?  Also, question from a colleague, for TEM specifically where diffraction patterns would fit into this PR?

2025-05-14 13:51 UTC, mkuehbach commented
@phyy-nx https://github.com/FAIRmat-NFDI/nexus_definitions/actions/runs/15020482132 here (at the bottom of the page to the right you find a downloadable artifact of the compiled documentation)
file:///<YOUR_PATH>/nexus-definitions-docs/classes/applications/NXem.html#nxem

2025-05-16 20:29 UTC, phyy-nx commented
From the Telco: need a few pages of introductory text and a figure that describes how to put this together, with maybe a couple example files.  Especially interested in a TEM example.  Thanks!

2025-05-19 17:12 UTC, mkuehbach commented
Add:
- [ ] gas_injector(NXcomponent)
- [ ] blankerID(NXdeflector)
- [ ] NX{e,i}beam_column and NXem

2025-05-21 15:40 UTC, mkuehbach commented
I added the request two-page introduction and contextualization for NXem, also I created a several figure drafts that may support the discussion as I am not yet fully decided which figure to pick and I also do not want to spent time with designing unnecessary inkscape sketches I dropped by drafts here:
@phyy-nx @yayahjb @sanbrock @lukaspie
https://github.com/FAIRmat-NFDI/nexus_definitions/pull/391#issuecomment-2898382358
Here is the compiled artifacts for the HTML documentation that includes the two-page top-level introduction but not the figure.

2025-06-06 12:24 UTC, mkuehbach commented
![NXem TopLevelDoc SEM 10](https://github.com/user-attachments/assets/b3c6405d-9a99-44f9-993c-2d0b033c3b65)

2025-06-06 12:26 UTC, mkuehbach commented
Building on the SEM, let's add FIB capabilities

![NXem TopLevelDoc FIB 10](https://github.com/user-attachments/assets/a1c8b3a2-f6fa-467c-8804-239661a4e7db)

**ADD FIGURE CAPTION for the SEM/FIB**

2025-06-06 12:28 UTC, mkuehbach commented
Finally let's go to a TEM, here a hybrid of a conventional TEM (that would not have a scan_controller) and a scanning TEM (which does) but I did not want to add yet another figure

![NXem TopLevelDoc TEM 10](https://github.com/user-attachments/assets/dabdc93a-d9a3-42df-8612-a889e448ca27)

**ADD FIGURE CAPTION for the TEM**

2025-06-06 12:29 UTC, mkuehbach commented
@phyy-nx @sanbrock @lukaspie @fsaizpoy here are candidates for the figures that were requested in one of the last telco's

2025-06-20 19:21 UTC, mkuehbach commented
@phyy-nx ready for review

2025-06-20 19:24 UTC, mkuehbach commented
Console with python virtual environment
```
https://github.com/FAIRmat-NFDI/nexus_definitions.git
cd nexus_definitions
make local
```
Navigate to ``nexus_definitions/build/manual/build/html/classes/contributed_definitions/em-structure.html#em-structure``

2025-06-20 20:11 UTC, mkuehbach commented
Observe that the last three commits add an example how we can modify the CI pipeline and latex build script to allow working with svg files. With the old sphinx and CI script this is not possible as svg is not supported out-of-the-box by latex. The here proposed solution renders the svg into png on the flight i.e. thereby the repository size will not grow as large as if we were to upload always rasterized images, for comparison, rendering the png locally with high resolution is a 1MB file, the svg is less than 100kb, the automatically rasterized png from the svg is a few hundred hundred kb, pipeline with these changes compiles now as well.

Apart from the typical benefits of vector over rasterized images, this solution is also more storage efficient because an svg file is a XML under the hood. It is the GitHub web interface which upon comparing the changes tries to sell this to us as an image. But moving or adding objects to an svg really is just like a source code change in that text file, most lines will remain untouched. I think this is a valuable solution for many other plots, of course unless really pictures are to be shown.

2025-06-23 08:21 UTC, mkuehbach commented
@phyy-nx @ercius left you a mail with example files, pull request is above, feedback to questions that were raised by Jordi Arbiol is here, https://github.com/FAIRmat-NFDI/nexus_definitions/pull/391 see the message from Jordi and Fernan and my replies in the conversation following up on these questions

2025-07-13 12:17 UTC, mkuehbach commented on base_classes/NXibeam_column.nxdl.xml
> +        <group name="probe" type="NXatom">
remove ionized

2025-07-13 12:19 UTC, mkuehbach commented on applications/NXem.nxdl.xml
> +                        <field name="mode" type="NX_CHAR">
make "operation_mode" as suggested by @fsaizpoy and @jarbiol-ICN2

2025-07-13 12:22 UTC, mkuehbach commented on manual/source/classes/contributed_definitions/em-structure.rst
> +**Fig. 2** - an example for a SEM with FIB capabilities
add plasma FIB, based on @jarbiol-ICN2 comment

2025-07-13 17:53 UTC, phyy-nx commented on applications/NXem.nxdl.xml
> +                start_time and end_time together.
I meant linking to `start_time`, but it's not urgent.

2025-07-16 20:59 UTC, mkuehbach commented
Request to change names of some base classes:
NXevent_data_apm > NXapm_event_data
NXevent_data_em > NXem_event_data
NXinteraction_volume_em > NXem_interaction_volume
NXlens_em > NXelectromagnetical_lens
NXoptical_system_em > NXem_optical_system
NXscanbox_em > NXscan_controller

2025-07-16 21:12 UTC, lukaspie commented
> Telco, NIAC request to change names of some base classes:
> 
> * [ ]  NXlens_em > NXmagnetic_lens

I suggest to use NXelectromagnetic_lens, so that electrostatic lenses in XPS are also covered.

2025-07-17 08:25 UTC, mkuehbach commented
@lukaspie @rettigl FYI - This PR will rename the base class NXlens_em to NXelectromagnetic_lens, might have practical consequences for datasets that you have already processed for NOMAD

2025-07-17 08:55 UTC, mkuehbach commented
Is complete, @phyy-nx voting can start

2025-07-17 16:43 UTC, mkuehbach commented
Hi Markus, NX_WAVENUMBER as units for the diffraction axis makes sense in theory, but oftentimes the calibration isn't right or even known to convert the pixel coordinates of the diffraction detector to reciprocal space coordinates.  Instead, we might want to store the diffraction data in pixels and rely on the NXdetector and NXbeam groups to calibrate and convert from pixels to reciprocal space coordinates.  Is this allowed/feasible in NXem?

Addressed via the last commit [31704f0](https://github.com/nexusformat/definitions/pull/1423/commits/31704f09aacc2a5a5d07d07f36b13568abc46c95)

2025-07-18 08:20 UTC, mkuehbach commented
@phyy-nx  another signature of support for NXem (found the paper again while cleaning up on my system):
```
With that said, we have identified standards that capture
the needs of the materials electron microscopy community.
For bibliographic information, the Dublin Core can provide
answers to who, what, where, and when. For microscopy con-
ditions we have found HMSA, now an ISO standard (ISO/DIS
5820 under development),20 and the NXem extension to the
NeXus file format provide an effective ontology for describing
materials EM instrument conditions.18
```
found here https://doi.org/10.1557/s43577-025-00882-2

2025-07-18 12:36 UTC, phyy-nx commented
Sweet find @mkuehbach!

2025-07-18 12:38 UTC, phyy-nx commented
Hi all, this PR can now be moved to a vote. Please votes using emoji's, 👍  for yes, 👎 for no, anything else e.g. 👀 for abstain. Voting will close in 2 weeks!

2025-07-28 15:05 UTC, rayosborn commented
There are a few files that I believe still don't follow the naming convention for domain-specific base classes, i.e., NXcorrector_cs, NXevent_data_em, and NXinstrument_em. I also note that NXaberration is documented as specific to the 'em' domain - should it be renamed NXem_aberration or do we think it is applicable as is to other uses of aberration corrections?

2025-07-29 08:15 UTC, mkuehbach commented
Wrt to @rayosborn comments:
- [ ] NXevent_data_em and NXevent_data_apm, before the voting for NXem started NXapm was already accepted with here the naming convention NXevent_data_apm used, so NXevent_data_em is consistent with this but not - agree with you Ray - consistent with many others which should follow the pattern NX<method>_<classname> so NXem_event_data and NXapm_event_data, as a solution I propose to change this in an immediate follow-up PR because changing it for both is changing the name of several classes during the vote and I do not want to risk touching or affecting the vote with such changes. I have implemented a solution via the follow-up proposal: ####
This renames NXevent_data_{apm,em}, NXinstrument_{em,apm}
- [ ] NXaberration, the exemplar literature snippets detail for electron microscopy, the class itself though is not limited to this research field only, a sentence was added to the top-level doc string to make this also clear.
- [ ] NXcorrector_cs as mentioned for NXaberration also here the docstring was modified to clarify that the class is not only applicable in electron microscopy, given that we have NXmonochromator, NXaperture, I do not suggest to add refactor to NXem_corrector_cs.

 I have implemented a solution via the follow-up proposal: 

> There are a few files that I believe still don't follow the naming convention for domain-specific base classes, i.e., NXcorrector_cs, NXevent_data_em, and NXinstrument_em. I also note that NXaberration is documented as specific to the 'em' domain - should it be renamed NXem_aberration or do we think it is applicable as is to other uses of aberration corrections?

2025-08-01 14:53 UTC, phyy-nx commented
Vote has passed. Thanks everyone!!

2025-08-01 14:54 UTC, phyy-nx approved these changes

2025-08-25 15:26 UTC, sanbrock commented
agreement from Telco: we can merge this PR, and then make a new PR from https://github.com/FAIRmat-NFDI/nexus_definitions/pull/402 and then merge that one, too.

2025-08-25 15:27 UTC, merged

2025-08-25 17:00 UTC, mkuehbach commented
Last comment addressed in #1585