Move `NXlens_em` to base classes
nexusformat/definitions pull request #1519
Opened 2024-12-09 16:59 UTC by lukaspie

This implements what was discussed in https://github.com/nexusformat/definitions/pull/1407#issuecomment-2528429712. It moves `NXlens_em` from the contributed definitions to the base classes and adds it to `NXsource` as an renameable group. 

Note that the difference between the `NXlens_em` from the contributed definitions and in base classes comes down to formatting, but no new terms have been added.

2024-12-18 17:00 UTC, phyy-nx commented
Comment from Telco:
- NXcomponent seems like a big change.  And that many base classes should derive from it.  The NIAC requests a survey of base classes to identify those which should and those which should not derive from NXcomponent.  Examples include NXdetector which should, and NXdata which should not.
- As a corollary, adding NXcomponent as a new parent class to classes such as NXdetector, NXbeam, etc., would be a significant change, so move NXcomponent to a new PR, and make this one dependent on that new PR

Alternate proposal: instead of NXcomponent, add the necessary new fields to NXobject.  This would imply that NXobject has NXfabrication and NXcircuit, but that's ok.  Better to have more possibilities on NXobject than to add more base classes in general.

Reviewed in the NIAC: took a straw poll and it was almost evenly split between the above two options.  This will need more discussion.  @nexusformat/developers please chime in here!  Thanks!

2024-12-19 16:09 UTC, lukaspie commented
> Comment from Telco:
> 
> * NXcomponent seems like a big change.  And that many base classes should derive from it.  The NIAC requests a survey of base classes to identify those which should and those which should not derive from NXcomponent.  Examples include NXdetector which should, and NXdata which should not.
> * As a corollary, adding NXcomponent as a new parent class to classes such as NXdetector, NXbeam, etc., would be a significant change, so move NXcomponent to a new PR, and make this one dependent on that new PR
> 
> Alternate proposal: instead of NXcomponent, add the necessary new fields to NXobject. This would imply that NXobject has NXfabrication and NXcircuit, but that's ok. Better to have more possibilities on NXobject than to add more base classes in general.
> 
> Reviewed in the NIAC: took a straw poll and it was almost evenly split between the above two options. This will need more discussion. @nexusformat/developers please chime in here! Thanks!

#1525 implements option 1 here and adds a list of all classes for which it would likely make sense to extend `NXcomponent`. This is more meant as an exploration/survey rather than a votable proposal.

2025-01-09 15:42 UTC, lukaspie commented
@phyy-nx @sanbrock @mkuehbach given that discussions around NXcomponent have not been settled yet (there is a new for this anyway, #1525), I moved it out this PR and just copied all relevant concepts to `NXlens_em` for now, so we can at least move forward with that one.

I think this PR is then ready to be discussion in one of the next Telcos.

2025-01-15 16:51 UTC, mkuehbach commented
> Note that `NXlens_em` itself is an extension of `NXcomponent` (which is meant as a basis for describing any components of an instrument).  `NXcomponent` is also making use of  `NXcircuit` (used for any sort of electronic circuit devices), so this is brought in here as well. These were originally to be discussed in #1424, but I think it's best to bring them in here.

NXcomponent was removed NXlens_em extends NXobject

2025-01-16 08:05 UTC, lukaspie commented
> > Note that `NXlens_em` itself is an extension of `NXcomponent` (which is meant as a basis for describing any components of an instrument).  `NXcomponent` is also making use of  `NXcircuit` (used for any sort of electronic circuit devices), so this is brought in here as well. These were originally to be discussed in #1424, but I think it's best to bring them in here.
> 
> NXcomponent was removed NXlens_em extends NXobject

Yes exactly, this is now implemented.

2025-01-27 16:01 UTC, phyy-nx commented on base_classes/NXlens_em.nxdl.xml
> +    <field name="value" type="NX_NUMBER" units="NX_ANY">
```suggestion
    <field name="power_setting" type="NX_NUMBER" units="NX_ANY">
```

2025-01-30 10:16 UTC, paulmillar commented on base_classes/NXlens_em.nxdl.xml
> +    <field name="power_setting" type="NX_NUMBER" units="NX_ANY">
I have no experience with EM, but an observation as an outsider ...

I'm wondering whether this value is continuous (accepting a very large number of different values) or whether this value accepts only a modest number of values.

If it's the latter, then it might be more flexible to consider the values as arbitrary labels that just coincidentally look like numbers (i.e., `type="NX_CHAR"`).  This would allow the field to capture non-numerical values, should EM manufacturers start to use them.

2025-01-30 10:18 UTC, paulmillar commented on base_classes/NXlens_em.nxdl.xml
> +    <field name="voltage" type="NX_NUMBER" units="NX_VOLTAGE">
Would it make sense to consider measured vs set points?  E.g., field `voltage` records the measured voltage while `voltage_set` describes the set point.

2025-01-30 10:20 UTC, paulmillar commented on base_classes/NXlens_em.nxdl.xml
> +    <field name="voltage" type="NX_NUMBER" units="NX_VOLTAGE">
Another point: the name is somewhat unfortunate -- just mirroring the units.

Would something like `name="control_voltage"` make sense?

2025-01-30 10:24 UTC, paulmillar commented on base_classes/NXsource.nxdl.xml
> +			Individual electromagnetic lenses inside the source.
Is the order of the `NXlens_em` significant?

2025-01-31 17:26 UTC, paulmillar commented on base_classes/NXlens_em.nxdl.xml
> +    <field name="power_setting" type="NX_NUMBER" units="NX_ANY">
OK, thanks for the explanation.  I think we can leave this until there's an actual need for it.

2025-01-31 17:29 UTC, paulmillar commented on base_classes/NXlens_em.nxdl.xml
> +    <field name="voltage" type="NX_NUMBER" units="NX_VOLTAGE">
OK.  Thanks for the feedback.

2025-01-31 17:30 UTC, paulmillar commented on base_classes/NXsource.nxdl.xml
> +			Individual electromagnetic lenses inside the source.
OK, thanks for the feedback.

2025-02-10 12:34 UTC, mkuehbach commented
> Is there another link for details of electro-magnetic lenses in the literature see e.g. `L. Reimer https://doi.org/10.1007/978-3-540-38967-5 ? It forwards to a whole book with a price of 245,-€ . This might be frustrating, if you don't have the book already and if you don't know what scanning elctron microscopy is, you sure don't have the book.

Possibly one could also point to
* https://www.globalsino.com/EM/ or more specifically to an example like
* https://www.globalsino.com/EM/page1985.html

In terms of scientific depth, coverage, and succinctness though these references
are weaker than is Reimer. Cheaper than Reimer and also useful e.g.
P. Hawkes, "Magnetic Electron Lenses", ISBN/EAN: 9783642815188

2025-02-13 00:05 UTC, phyy-nx requested changes
Vote has failed. We will discuss the review in tomorrow's telco.

2025-02-13 16:16 UTC, sanbrock commented
After fixing the reference, we can run the vote again.

2025-02-13 17:44 UTC, lukaspie commented
> After fixing the reference, we can run the vote again.

Added references to all the resources given above, so the NeXus user has some choices.

@sanbrock @phyy-nx please feel free to initiate another vote.

2025-02-18 23:31 UTC, phyy-nx commented
Hi all, as discussed in the Telco, we try again as an online vote. NIAC committee members please vote on this PR using emojis on this comment. 👍 for yes, 👎 for no, anything else (for example 👀) to abstain. We need 14 votes to hit quorum so please review and vote!

2025-02-24 21:34 UTC, tacaswell commented
Was there any discussion of applying this to the elements in a storage ring?

2025-02-24 21:37 UTC, phyy-nx commented
> Was there any discussion of applying this to the elements in a storage ring?

Interesting.  Do you mean like describing the upstream optical focusing elements at something like a synchrotron?

2025-02-24 21:59 UTC, tacaswell commented
> Do you mean like describing the upstream optical focusing elements at something like a synchrotron?

Yes.  However I don't know enough about how the accelerator folks describe the lattice to know if it sensible to try and interoperate with the electron microscope lens descriptions beyond the superficial (N-pole magnets focusing / steering electron beams).

2025-02-24 22:08 UTC, phyy-nx commented
> > Do you mean like describing the upstream optical focusing elements at something like a synchrotron?
> 
> Yes. However I don't know enough about how the accelerator folks describe the lattice to know if it sensible to try and interoperate with the electron microscope lens descriptions beyond the superficial (N-pole magnets focusing / steering electron beams).

Likewise, but I like the idea...

2025-02-25 09:37 UTC, fsaizpoy commented
Hi Lukas,
Is NXlens_em also intended to be used to describe PEEM microscopes?

2025-02-26 09:07 UTC, lukaspie commented
> Hi Lukas, Is NXlens_em also intended to be used to describe PEEM microscopes?

We have not considered it for PEEM yet. Mostly `NXlens_em` was designed for electron microscopes (SEM, TEM) and for the electromagnetic lenses in photoelectron spectrometers. We have a draft for an application definition for PEEM (https://github.com/FAIRmat-NFDI/nexus_definitions/pull/147) together with @PeterC-DLS, but there has been not much work in this direction for some time. I think most concepts in `NXlens_em` would be applicable for PEEMs as well though.

2025-03-04 22:03 UTC, phyy-nx approved these changes
The vote has passed, thanks everyone.  @lukaspie feel free to merge.

2025-03-04 22:20 UTC, merged