refactor anyUnitsAttr - re-examine
nexusformat/definitions pull request #683
Opened 2019-09-11 13:35 UTC by prjemian

fixes #555

2019-09-11 14:23 UTC, prjemian commented
need to merge master into this branch

2020-01-23 19:12 UTC, prjemian commented
Willing to wait on this until next milestone.  Today's release will then be merged into this PR, making it easier to resolve what actually will be changed.

2020-10-12 23:17 UTC, prjemian commented
Can this be merged now?

2020-10-14 19:52 UTC, prjemian commented
@PeterC-DLS Could you review this?

2020-10-15 08:20 UTC, PeterC-DLS requested changes

2020-10-15 08:20 UTC, PeterC-DLS commented on base_classes/NXtransformations.nxdl.xml
> +
Leave this file unchanged

2020-10-15 15:06 UTC, prjemian commented on base_classes/NXtransformations.nxdl.xml
> +
done

2020-10-15 15:08 UTC, PeterC-DLS approved these changes

2020-10-15 15:15 UTC, prjemian commented
Thanks for the review.  This is not waiting on any vote so I'll merge now so there will not be another merge conflict if any of the existing PRs are merged.  I expect each one of those may need to be rebased to master before they are merged.

2020-10-15 15:15 UTC, merged