recommend providing time zone in NX_DATE_TIME
nexusformat/definitions pull request #806
Opened 2020-10-13 17:58 UTC by prjemian

fixes #805

2020-10-16 10:44 UTC, PeterC-DLS requested changes
Can you separate out the whitespace changes and text reflow from this PR?

2020-10-19 09:10 UTC, PeterC-DLS approved these changes
LGTM. Does raise the issue of where the local time zone is recorded.

2020-10-19 09:51 UTC, vasole commented
@PeterC-DLS 

To me it is enough to specify your local time zone in the ISO8601.

As far as I understand this proposal, you can provide any time zone. What is needed is to remove the ambiguity when there is no time zone specified. The norm is that if there is no time zone, it is assumed local time, however, when a file moves from one country to another it is undefined. If the local time zone is written, the ambiguity is gone.

2020-10-19 18:32 UTC, yayahjb approved these changes

2020-10-19 18:32 UTC, merged