reserved prefixes for names
nexusformat/definitions pull request #808
Opened 2020-10-13 19:11 UTC by prjemian

fixes #769

2020-10-13 19:15 UTC, prjemian commented
wait for merge pending outcome of [NIAC2020 vote](https://github.com/nexusformat/NIAC/issues/49#issuecomment-707383140)

2020-10-14 09:27 UTC, PeterC-DLS requested changes

2020-10-14 09:27 UTC, PeterC-DLS commented on manual/source/datarules.rst
> +When naming a field (or dataset), NeXus has reserved certain prefixes to
Remove "(or dataset)" to make terminolgy consistent

2020-10-14 09:27 UTC, PeterC-DLS commented on manual/source/datarules.rst
> +``NX``      NXDL class 	For the class names used with NeXus groups 	https://www.nexusformat.org
consistent uncapitalization of "For"

2020-10-14 22:00 UTC, yayahjb approved these changes

2020-10-14 22:01 UTC, yayahjb commented
A good step forward

2020-10-15 06:08 UTC, vasole approved these changes
Thanks

2020-10-16 10:46 UTC, PeterC-DLS approved these changes

2020-10-25 20:13 UTC, benajamin approved these changes

2020-11-03 13:56 UTC, merged