Add BLUESKY_ as a reserved prefix
nexusformat/definitions pull request #873
Opened 2020-12-07 19:24 UTC by stuartcampbell

As discussed in https://github.com/nexusformat/NIAC/issues/80

2020-12-07 20:28 UTC, benajamin approved these changes

2020-12-07 22:17 UTC, prjemian approved these changes

2020-12-07 22:21 UTC, prjemian requested changes
the alignment is off in the table of reserved prefixes, somehow the checks miss this detail, but the restructured text will not format properly

2020-12-08 08:42 UTC, PeterC-DLS approved these changes

2020-12-08 10:06 UTC, PeterC-DLS commented
> 
> 
> the alignment is off in the table of reserved prefixes, somehow the checks miss this detail, but the restructured text will not format properly

Done

2020-12-08 10:06 UTC, merged